baseURL = "https://wilspi.com"
languageCode = "en-us"
title = "wilspi | Sourabh Deokar"
theme = "PaperMod"

enableEmoji = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false


## Google Analytics
googleAnalytics = "UA-51915090-3"


[params]
title = "‡§®‡§Æ‡§∏‡•ç‡§§‡•á"
author = "wilspi"
description = "Hi there! üëã My name is Sourabh Deokar, and I share my learnings, musings and experiences here. Welcome to my blog!"
profilePicture = "images/dp.jpg"

env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
#images = ["<link or path of image for opengraph, twitter-cards>"]

defaultTheme = "auto" # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
disableSpecial1stPost = true
comments = false
hidemeta = false
showtoc = false
tocopen = false

keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/cover.jpg"]


[params.assets]
favicon = "favicons/favicon.ico"
favicon16x16 = "favicons/favicon-16x16.png"
favicon32x32 = "favicons/favicon-32x32.png"
apple_touch_icon = "favicons/apple-touch-icon.png"
# safari_pinned_tab: "<link / abs url>"

[params.profileMode]
enabled = false # needs to be explicitly set
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "images/cover.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"
# buttons:
#         - name: Posts
#           url: posts
#         - name: Tags
#           url: tags

# home-info mode
[params.homeInfoParams]
Title = "Hi there \U0001F44B"
Content = "My name is Sourabh Deokar, and I share my learnings, musings and experiences here. Welcome to my blog!"




## Math settings
[params.math]
enable = false
use = "katex"


## Social links
[[params.socialIcons]]
icon = "fa-github"
name = "GitHub"
url = "https://github.com/wilspi/"

[[params.socialIcons]]
icon = "fa-youtube"
name = "Youtube"
url = "https://www.youtube.com/channel/UCeOPNskzsoFb6b8oUn0oEMA"

[[params.socialIcons]]
icon = "fa-twitter"
name = "Twitter"
url = "https://www.twitter.com/iamwilspi"

# [[params.socialIcons]]
# icon = "fa-instagram"
# title = "Instagram"
# url = "https://www.instagram.com/wilspi/"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  # [[menu.main]]
  # name = "Notes"
  # identifier = ""
  # weight = 100
  # url = "https://notes.wilspi.com"

  # [[menu.main]]
  # name = "Posts"
  # weight = 200
  # identifier = "posts"
  # url = "/post/"

  # [[menu.main]]
  # name = "About"
  # weight = 300
  # identifier = "about"
  # url = "/about/"
